# Site settings
title: Dr. Timothy W. Hnat - Assistant Professor
email: hnat@timothyhnat.com
description: ""
baseurl: ""
url: "http://www.timothyhnat.com"
twitter_username: timothy.hnat
github_username:  twhnat

# Build settings
markdown: kramdown
permalink: pretty

links:
    -   title: Photography
        url: http://photos.timothyhnat.com/

    -   title: Publications
        url: /publications/

    -   title: Resume/CV
        url: /resources/resume.pdf
