# Site settings
title: Dr. Timothy W. Hnat
email: hnat@timothyhnat.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://www.timothyhnat.com"
twitter_username: timothy.hnat
github_username:  twhnat

# Build settings
markdown: kramdown
permalink: pretty
